"""baseline_from_current_models

Revision ID: 40ca71c79446
Revises: 
Create Date: 2026-06-03 20:47:02.596467

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "40ca71c79446"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("server", sa.String(length=255), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("last_sync", sa.DateTime(), nullable=True),
        sa.Column("last_sync_status", sa.String(length=50), nullable=True),
        sa.Column("sync_in_progress", sa.Boolean(), nullable=True),
        sa.Column("sync_started_at", sa.DateTime(), nullable=True),
        sa.Column("ppv_visibility", sa.String(length=20), nullable=False),
        sa.Column("ppv_rename_format", sa.Text(), nullable=True),
        sa.Column("ppv_rename_timezone", sa.String(length=50), nullable=True),
        sa.Column("fcc_rename_format", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cached_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("original_url", sa.String(length=2000), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("fetch_count", sa.Integer(), nullable=True),
        sa.Column("hit_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cached_images", schema=None) as batch_op:
        batch_op.create_index("idx_cached_image_expires", ["expires_at"], unique=False)
        batch_op.create_index("idx_cached_image_status", ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_cached_images_url_hash"), ["url_hash"], unique=True)

    op.create_table(
        "callsign_suffixes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("suffix", sa.String(length=10), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.Column("try_on_miss", sa.Boolean(), nullable=True),
        sa.Column("strip_on_normalize", sa.Boolean(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("suffix"),
    )
    op.create_table(
        "channel_health_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "country_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag_name", sa.String(length=10), nullable=False),
        sa.Column("country_name", sa.String(length=100), nullable=True),
        sa.Column("iso_code", sa.String(length=3), nullable=True),
        sa.Column("exclude_from_location", sa.Boolean(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag_name"),
    )
    op.create_table(
        "epg_channel_name_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("old_name", sa.String(length=200), nullable=False),
        sa.Column("new_name", sa.String(length=200), nullable=False),
        sa.Column("match_type", sa.String(length=20), nullable=False),
        sa.Column("case_sensitive", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "epg_country_suffixes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country_code", sa.String(length=10), nullable=False),
        sa.Column("country_name", sa.String(length=100), nullable=True),
        sa.Column("epg_suffixes", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("country_code"),
    )
    op.create_table(
        "epg_exclusion_patterns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("pattern_type", sa.String(length=30), nullable=False),
        sa.Column("pattern", sa.String(length=500), nullable=False),
        sa.Column("is_regex", sa.Boolean(), nullable=True),
        sa.Column("hide_channel", sa.Boolean(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "epg_match_rulesets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=50), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("sport", sa.String(length=100), nullable=True),
        sa.Column("league_id", sa.String(length=50), nullable=True),
        sa.Column("league_name", sa.String(length=200), nullable=True),
        sa.Column("home_team_id", sa.String(length=50), nullable=False),
        sa.Column("home_team_name", sa.String(length=200), nullable=False),
        sa.Column("away_team_id", sa.String(length=50), nullable=False),
        sa.Column("away_team_name", sa.String(length=200), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column("start_at", sa.DateTime(), nullable=True),
        sa.Column("end_at", sa.DateTime(), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("venue_id", sa.String(length=50), nullable=True),
        sa.Column("venue_name", sa.String(length=200), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("event_metadata", sa.Text(), nullable=True),
        sa.Column("home_team_badge", sa.String(length=500), nullable=True),
        sa.Column("away_team_badge", sa.String(length=500), nullable=True),
        sa.Column("event_image", sa.String(length=500), nullable=True),
        sa.Column("is_ppv", sa.Boolean(), nullable=True),
        sa.Column("ppv_price", sa.String(length=50), nullable=True),
        sa.Column("ppv_availability", sa.Text(), nullable=True),
        sa.Column("data_completeness", sa.String(length=20), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id", "source", name="uq_event_external_id_source"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index("idx_event_league", ["league_id"], unique=False)
        batch_op.create_index("idx_event_scheduled", ["scheduled_at"], unique=False)
        batch_op.create_index("idx_event_teams", ["home_team_id", "away_team_id"], unique=False)
        batch_op.create_index("idx_event_title", ["title"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_away_team_id"), ["away_team_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_away_team_name"), ["away_team_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_external_id"), ["external_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_home_team_id"), ["home_team_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_home_team_name"), ["home_team_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_is_ppv"), ["is_ppv"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_league_id"), ["league_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_league_name"), ["league_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_scheduled_at"), ["scheduled_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_sport"), ["sport"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_start_at"), ["start_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_title"), ["title"], unique=False)

    op.create_table(
        "fcc_corrections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("callsign", sa.String(length=20), nullable=False),
        sa.Column("facility_id", sa.Integer(), nullable=True),
        sa.Column("network_affiliation", sa.String(length=100), nullable=True),
        sa.Column("tv_virtual_channel", sa.String(length=10), nullable=True),
        sa.Column("nielsen_dma", sa.String(length=100), nullable=True),
        sa.Column("community_city", sa.String(length=100), nullable=True),
        sa.Column("community_state", sa.String(length=10), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("callsign", "facility_id", name="uq_fcc_correction_callsign_facility"),
    )
    with op.batch_alter_table("fcc_corrections", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fcc_corrections_callsign"), ["callsign"], unique=False)
        batch_op.create_index(batch_op.f("ix_fcc_corrections_facility_id"), ["facility_id"], unique=False)

    op.create_table(
        "fcc_facilities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("facility_id", sa.Integer(), nullable=True),
        sa.Column("callsign", sa.String(length=20), nullable=False),
        sa.Column("service_code", sa.String(length=10), nullable=True),
        sa.Column("station_type", sa.String(length=10), nullable=True),
        sa.Column("community_city", sa.String(length=100), nullable=True),
        sa.Column("community_state", sa.String(length=10), nullable=True),
        sa.Column("channel", sa.String(length=10), nullable=True),
        sa.Column("tv_virtual_channel", sa.String(length=10), nullable=True),
        sa.Column("network_affiliation", sa.String(length=100), nullable=True),
        sa.Column("nielsen_dma", sa.String(length=100), nullable=True),
        sa.Column("nielsen_dma_rank", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("facility_status", sa.String(length=20), nullable=True),
        sa.Column("last_update", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fcc_facilities", schema=None) as batch_op:
        batch_op.create_index("idx_fcc_callsign_service", ["callsign", "service_code"], unique=False)
        batch_op.create_index("idx_fcc_city_state", ["community_city", "community_state"], unique=False)
        batch_op.create_index("idx_fcc_dma", ["nielsen_dma"], unique=False)
        batch_op.create_index("idx_fcc_network", ["network_affiliation"], unique=False)
        batch_op.create_index(batch_op.f("ix_fcc_facilities_callsign"), ["callsign"], unique=False)
        batch_op.create_index(batch_op.f("ix_fcc_facilities_community_city"), ["community_city"], unique=False)
        batch_op.create_index(batch_op.f("ix_fcc_facilities_community_state"), ["community_state"], unique=False)
        batch_op.create_index(batch_op.f("ix_fcc_facilities_facility_id"), ["facility_id"], unique=True)

    op.create_table(
        "fcc_match_channel_patterns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("pattern", sa.Text(), nullable=False),
        sa.Column("pattern_type", sa.String(length=20), nullable=True),
        sa.Column("capture_group", sa.Integer(), nullable=True),
        sa.Column("networks", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fcc_match_location_patterns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("pattern", sa.Text(), nullable=False),
        sa.Column("pattern_type", sa.String(length=20), nullable=True),
        sa.Column("extract_city", sa.Boolean(), nullable=True),
        sa.Column("extract_state", sa.Boolean(), nullable=True),
        sa.Column("city_group", sa.Integer(), nullable=True),
        sa.Column("state_group", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fcc_match_networks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("fcc_affiliation_pattern", sa.String(length=200), nullable=False),
        sa.Column("tag_patterns", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "fcc_match_strategies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("strategy_type", sa.String(length=50), nullable=False),
        sa.Column("require_network", sa.Boolean(), nullable=True),
        sa.Column("require_channel_number", sa.Boolean(), nullable=True),
        sa.Column("require_state", sa.Boolean(), nullable=True),
        sa.Column("require_city", sa.Boolean(), nullable=True),
        sa.Column("match_nielsen_dma", sa.Boolean(), nullable=True),
        sa.Column("match_community_city", sa.Boolean(), nullable=True),
        sa.Column("match_community_state", sa.Boolean(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playlist_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("include_accounts", sa.Text(), nullable=True),
        sa.Column("exclude_accounts", sa.Text(), nullable=True),
        sa.Column("include_tags", sa.Text(), nullable=True),
        sa.Column("exclude_tags", sa.Text(), nullable=True),
        sa.Column("tag_match_mode", sa.String(length=10), nullable=True),
        sa.Column("preferred_languages", sa.Text(), nullable=True),
        sa.Column("language_fallback", sa.String(length=20), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("playlist_configs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_playlist_configs_slug"), ["slug"], unique=True)

    op.create_table(
        "provider_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_name", sa.String(length=100), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_name", "key", name="uq_provider_settings_name_key"),
    )
    with op.batch_alter_table("provider_settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_provider_settings_provider_name"), ["provider_name"], unique=False)

    op.create_table(
        "quality_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag_name", sa.String(length=20), nullable=False),
        sa.Column("display_name", sa.String(length=50), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=True),
        sa.Column("quality_score", sa.Integer(), nullable=True),
        sa.Column("exclude_from_location", sa.Boolean(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag_name"),
    )
    op.create_table(
        "rulesets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "sports_teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sport", sa.String(length=20), nullable=False),
        sa.Column("abbreviation", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("aliases", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=10), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("venue_name", sa.String(length=200), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("iana_timezone", sa.String(length=50), nullable=True),
        sa.Column("location_source", sa.String(length=100), nullable=True),
        sa.Column("conference", sa.String(length=100), nullable=True),
        sa.Column("division", sa.String(length=100), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sport", "abbreviation", name="uq_sports_team_sport_abbrev"),
    )
    with op.batch_alter_table("sports_teams", schema=None) as batch_op:
        batch_op.create_index("idx_sports_team_name", ["name"], unique=False)
        batch_op.create_index("idx_sports_team_sport", ["sport"], unique=False)
        batch_op.create_index(batch_op.f("ix_sports_teams_abbreviation"), ["abbreviation"], unique=False)
        batch_op.create_index(batch_op.f("ix_sports_teams_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_sports_teams_sport"), ["sport"], unique=False)

    op.create_table(
        "sync_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tags_name"), ["name"], unique=True)

    op.create_table(
        "account_epg_match_rulesets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("ruleset_id", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["ruleset_id"],
            ["epg_match_rulesets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "ruleset_id", name="_account_epg_match_ruleset_uc"),
    )
    op.create_table(
        "account_rulesets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("ruleset_id", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["ruleset_id"],
            ["rulesets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "ruleset_id", name="_account_ruleset_uc"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.String(length=50), nullable=False),
        sa.Column("category_name", sa.String(length=200), nullable=False),
        sa.Column("cleaned_name", sa.String(length=200), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_ppv", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "category_id", name="_account_category_uc"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index("idx_category_account", ["account_id"], unique=False)
        batch_op.create_index("idx_category_ppv", ["is_ppv"], unique=False)
        batch_op.create_index(batch_op.f("ix_categories_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_categories_is_ppv"), ["is_ppv"], unique=False)

    op.create_table(
        "channel_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("stream_id", sa.String(length=50), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "stream_id", "tag_id", name="_channel_tag_uc"),
    )
    with op.batch_alter_table("channel_tags", schema=None) as batch_op:
        batch_op.create_index("idx_channel_tags_account_stream", ["account_id", "stream_id"], unique=False)
        batch_op.create_index("idx_channel_tags_account_tag", ["account_id", "tag_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_tags_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_tags_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_tags_tag_id"), ["tag_id"], unique=False)

    op.create_table(
        "credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("max_connections", sa.Integer(), nullable=True),
        sa.Column("active_connections", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("exp_date", sa.String(length=50), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("credentials", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_credentials_account_id"), ["account_id"], unique=False)

    op.create_table(
        "epg_match_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ruleset_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("match_type", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=True),
        sa.Column("pattern", sa.String(length=500), nullable=True),
        sa.Column("action", sa.String(length=20), nullable=True),
        sa.Column("min_confidence", sa.Float(), nullable=True),
        sa.Column("required_tags", sa.Text(), nullable=True),
        sa.Column("excluded_tags", sa.Text(), nullable=True),
        sa.Column("fallback_epg_id", sa.String(length=100), nullable=True),
        sa.Column("category_pattern", sa.String(length=500), nullable=True),
        sa.Column("category_exclude_pattern", sa.String(length=500), nullable=True),
        sa.Column("country_codes", sa.Text(), nullable=True),
        sa.Column("epg_source_ids", sa.Text(), nullable=True),
        sa.Column("time_offset_hours", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("stop_on_match", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["ruleset_id"], ["epg_match_rulesets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "epg_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("sd_username", sa.String(length=100), nullable=True),
        sa.Column("sd_password", sa.String(length=100), nullable=True),
        sa.Column("xmltv_grabber", sa.String(length=100), nullable=True),
        sa.Column("xmltv_config_name", sa.String(length=100), nullable=True),
        sa.Column("xmltv_days", sa.Integer(), nullable=True),
        sa.Column("xmltv_offset", sa.Integer(), nullable=True),
        sa.Column("xmltv_extra_args", sa.JSON(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("last_sync", sa.DateTime(), nullable=True),
        sa.Column("last_sync_status", sa.String(length=50), nullable=True),
        sa.Column("last_sync_message", sa.Text(), nullable=True),
        sa.Column("channel_count", sa.Integer(), nullable=True),
        sa.Column("sync_in_progress", sa.Boolean(), nullable=True),
        sa.Column("sync_phase", sa.String(length=50), nullable=True),
        sa.Column("sync_progress", sa.JSON(), nullable=True),
        sa.Column("sync_started_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("epg_sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_epg_sources_account_id"), ["account_id"], unique=False)

    op.create_table(
        "filters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("filter_type", sa.String(length=50), nullable=False),
        sa.Column("filter_action", sa.String(length=20), nullable=False),
        sa.Column("filter_value", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tag_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ruleset_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("pattern", sa.String(length=255), nullable=False),
        sa.Column("pattern_type", sa.String(length=20), nullable=False),
        sa.Column("tag_name", sa.String(length=50), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("remove_from_name", sa.Boolean(), nullable=True),
        sa.Column("replacement", sa.String(length=255), nullable=True),
        sa.Column("set_is_ppv", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ruleset_id"],
            ["rulesets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "xtream_credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("playlist_config_id", sa.Integer(), nullable=True),
        sa.Column("use_filters", sa.Boolean(), nullable=True),
        sa.Column("collapse_duplicates", sa.Boolean(), nullable=True),
        sa.Column("ppv_rename_timezone", sa.String(length=50), nullable=True),
        sa.Column("preferred_languages", sa.Text(), nullable=True),
        sa.Column("language_fallback", sa.String(length=20), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["playlist_config_id"],
            ["playlist_configs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("xtream_credentials", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_xtream_credentials_account_id"), ["account_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_xtream_credentials_playlist_config_id"), ["playlist_config_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_xtream_credentials_username"), ["username"], unique=True)

    op.create_table(
        "active_streams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.Integer(), nullable=False),
        sa.Column("stream_id", sa.String(length=50), nullable=False),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.Column("session_token", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("last_activity", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["credential_id"], ["credentials.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_token"),
    )
    with op.batch_alter_table("active_streams", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_active_streams_credential_id"), ["credential_id"], unique=False)

    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("stream_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("cleaned_name", sa.String(length=500), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("stream_type", sa.String(length=20), nullable=True),
        sa.Column("stream_icon", sa.String(length=500), nullable=True),
        sa.Column("epg_channel_id", sa.String(length=100), nullable=True),
        sa.Column("added", sa.String(length=50), nullable=True),
        sa.Column("custom_sid", sa.String(length=50), nullable=True),
        sa.Column("tv_archive", sa.Integer(), nullable=True),
        sa.Column("direct_source", sa.String(length=500), nullable=True),
        sa.Column("tv_archive_duration", sa.Integer(), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_visible", sa.Boolean(), nullable=True),
        sa.Column("is_ppv", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("thesportsdb_id", sa.String(length=50), nullable=True),
        sa.Column("fcc_facility_id", sa.Integer(), nullable=True),
        sa.Column("ppv_enrichment_status", sa.String(length=20), nullable=True),
        sa.Column("ppv_enrichment_queue_id", sa.String(length=100), nullable=True),
        sa.Column("ppv_enrichment_attempts", sa.Integer(), nullable=True),
        sa.Column("ppv_enrichment_error", sa.Text(), nullable=True),
        sa.Column("ppv_enrichment_last_attempt", sa.DateTime(), nullable=True),
        sa.Column("broadcast_language", sa.String(length=10), nullable=True),
        sa.Column("language_source", sa.String(length=30), nullable=True),
        sa.Column("language_confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["fcc_facility_id"],
            ["fcc_facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "stream_id", name="_account_stream_uc"),
    )
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.create_index("idx_channel_account", ["account_id"], unique=False)
        batch_op.create_index("idx_channel_category", ["category_id"], unique=False)
        batch_op.create_index("idx_channel_name", ["name"], unique=False)
        batch_op.create_index("ix_channel_ppv_queue", ["is_ppv", "ppv_enrichment_status", "last_seen"], unique=False)
        batch_op.create_index(batch_op.f("ix_channels_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_channels_category_id"), ["category_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_channels_fcc_facility_id"), ["fcc_facility_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_channels_is_ppv"), ["is_ppv"], unique=False)
        batch_op.create_index(batch_op.f("ix_channels_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_channels_ppv_enrichment_queue_id"), ["ppv_enrichment_queue_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_channels_ppv_enrichment_status"), ["ppv_enrichment_status"], unique=False)
        batch_op.create_index(batch_op.f("ix_channels_thesportsdb_id"), ["thesportsdb_id"], unique=False)

    op.create_table(
        "epg_channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("display_names_json", sa.JSON(), nullable=True),
        sa.Column("icon_url", sa.String(length=500), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("matched_channels_json", sa.JSON(), nullable=True),
        sa.Column("program_count", sa.Integer(), nullable=True),
        sa.Column("first_program", sa.DateTime(), nullable=True),
        sa.Column("last_program", sa.DateTime(), nullable=True),
        sa.Column("schedule_md5", sa.String(length=32), nullable=True),
        sa.Column("schedule_last_modified", sa.DateTime(), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["epg_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "channel_id", name="_source_channel_uc"),
    )
    with op.batch_alter_table("epg_channels", schema=None) as batch_op:
        batch_op.create_index("idx_epg_channel_id", ["channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_channels_channel_id"), ["channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_channels_source_id"), ["source_id"], unique=False)

    op.create_table(
        "sd_lineups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("epg_source_id", sa.Integer(), nullable=False),
        sa.Column("lineup_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("lineup_type", sa.String(length=50), nullable=True),
        sa.Column("transport", sa.String(length=50), nullable=True),
        sa.Column("channel_count", sa.Integer(), nullable=True),
        sa.Column("last_sync", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["epg_source_id"], ["epg_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("epg_source_id", "lineup_id", name="_source_lineup_uc"),
    )
    with op.batch_alter_table("sd_lineups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sd_lineups_epg_source_id"), ["epg_source_id"], unique=False)

    op.create_table(
        "channel_epg_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("epg_channel_id", sa.Integer(), nullable=False),
        sa.Column("mapping_type", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("time_offset_hours", sa.Integer(), nullable=True),
        sa.Column("is_override", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["epg_channel_id"], ["epg_channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id", "epg_channel_id", name="_channel_epg_mapping_uc"),
    )
    with op.batch_alter_table("channel_epg_mappings", schema=None) as batch_op:
        batch_op.create_index("idx_channel_epg_channel", ["channel_id"], unique=False)
        batch_op.create_index("idx_epg_channel_mapping", ["epg_channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_epg_mappings_channel_id"), ["channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_epg_mappings_epg_channel_id"), ["epg_channel_id"], unique=False)

    op.create_table(
        "channel_health_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("http_status_code", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("analysis_details", sa.Text(), nullable=True),
        sa.Column("check_duration_ms", sa.Integer(), nullable=True),
        sa.Column("checked_at", sa.DateTime(), nullable=False),
        sa.Column("credential_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credentials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("channel_health_checks", schema=None) as batch_op:
        batch_op.create_index("idx_health_check_channel_time", ["channel_id", "checked_at"], unique=False)
        batch_op.create_index("idx_health_check_result", ["result"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_health_checks_channel_id"), ["channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_health_checks_checked_at"), ["checked_at"], unique=False)

    op.create_table(
        "channel_health_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_checks", sa.Integer(), nullable=True),
        sa.Column("successful_checks", sa.Integer(), nullable=True),
        sa.Column("failed_checks", sa.Integer(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=True),
        sa.Column("last_success_at", sa.DateTime(), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(), nullable=True),
        sa.Column("last_check_at", sa.DateTime(), nullable=True),
        sa.Column("last_result", sa.String(length=30), nullable=True),
        sa.Column("distinct_failure_periods", sa.Integer(), nullable=True),
        sa.Column("auto_disabled_at", sa.DateTime(), nullable=True),
        sa.Column("manually_reenabled_at", sa.DateTime(), nullable=True),
        sa.Column("ignored_at", sa.DateTime(), nullable=True),
        sa.Column("ignored_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id"),
    )
    with op.batch_alter_table("channel_health_status", schema=None) as batch_op:
        batch_op.create_index("idx_health_status_status", ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_health_status_status"), ["status"], unique=False)

    op.create_table(
        "channel_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("source_channel_id", sa.Integer(), nullable=False),
        sa.Column("time_offset_hours", sa.Integer(), nullable=True),
        sa.Column("link_type", sa.String(length=50), nullable=True),
        sa.Column("auto_detected", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id", "source_channel_id", name="_channel_link_uc"),
    )
    with op.batch_alter_table("channel_links", schema=None) as batch_op:
        batch_op.create_index("idx_channel_link_channel", ["channel_id"], unique=False)
        batch_op.create_index("idx_channel_link_source", ["source_channel_id"], unique=False)

    op.create_table(
        "epg_programs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("epg_channel_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("stop_time", sa.DateTime(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("sub_title", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("categories", sa.JSON(), nullable=True),
        sa.Column("season", sa.Integer(), nullable=True),
        sa.Column("episode", sa.Integer(), nullable=True),
        sa.Column("episode_id", sa.String(length=100), nullable=True),
        sa.Column("rating", sa.String(length=20), nullable=True),
        sa.Column("rating_system", sa.String(length=50), nullable=True),
        sa.Column("original_air_date", sa.Date(), nullable=True),
        sa.Column("is_new", sa.Boolean(), nullable=True),
        sa.Column("is_live", sa.Boolean(), nullable=True),
        sa.Column("is_premiere", sa.Boolean(), nullable=True),
        sa.Column("sport", sa.String(length=100), nullable=True),
        sa.Column("team_home", sa.String(length=200), nullable=True),
        sa.Column("team_away", sa.String(length=200), nullable=True),
        sa.Column("icon_url", sa.String(length=500), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["epg_channel_id"], ["epg_channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("epg_channel_id", "start_time", name="_epg_program_channel_start_uc"),
    )
    with op.batch_alter_table("epg_programs", schema=None) as batch_op:
        batch_op.create_index(
            "idx_epg_program_channel_time", ["epg_channel_id", "start_time", "stop_time"], unique=False
        )
        batch_op.create_index("idx_epg_program_start", ["start_time"], unique=False)
        batch_op.create_index("idx_epg_program_stop", ["stop_time"], unique=False)
        batch_op.create_index("idx_epg_program_title", ["title"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_programs_epg_channel_id"), ["epg_channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_programs_start_time"), ["start_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_programs_stop_time"), ["stop_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_programs_title"), ["title"], unique=False)

    op.create_table(
        "event_channel_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("feed_type", sa.String(length=50), nullable=True),
        sa.Column("region", sa.String(length=50), nullable=True),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("match_confidence", sa.Float(), nullable=True),
        sa.Column("match_method", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "channel_id", name="_event_channel_uc"),
    )
    with op.batch_alter_table("event_channel_links", schema=None) as batch_op:
        batch_op.create_index("idx_event_channel_channel", ["channel_id"], unique=False)
        batch_op.create_index("idx_event_channel_event", ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_event_channel_links_channel_id"), ["channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_event_channel_links_event_id"), ["event_id"], unique=False)

    op.create_table(
        "sd_lineup_sync_status",
        sa.Column("lineup_id", sa.Integer(), nullable=False),
        sa.Column("sync_in_progress", sa.Boolean(), nullable=True),
        sa.Column("sync_phase", sa.String(length=50), nullable=True),
        sa.Column("sync_progress", sa.Text(), nullable=True),
        sa.Column("sync_started_at", sa.DateTime(), nullable=True),
        sa.Column("last_sync", sa.DateTime(), nullable=True),
        sa.Column("last_sync_status", sa.String(length=50), nullable=True),
        sa.Column("last_sync_message", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["lineup_id"], ["sd_lineups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("lineup_id"),
    )
    op.create_table(
        "sd_stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lineup_id", sa.Integer(), nullable=False),
        sa.Column("station_id", sa.String(length=50), nullable=False),
        sa.Column("channel_number", sa.String(length=20), nullable=True),
        sa.Column("callsign", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("affiliate", sa.String(length=100), nullable=True),
        sa.Column("broadcast_language", sa.JSON(), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["lineup_id"], ["sd_lineups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lineup_id", "station_id", name="_lineup_station_uc"),
    )
    with op.batch_alter_table("sd_stations", schema=None) as batch_op:
        batch_op.create_index("idx_sd_station_callsign", ["callsign"], unique=False)
        batch_op.create_index("idx_sd_station_name", ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_sd_stations_lineup_id"), ["lineup_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sd_stations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sd_stations_lineup_id"))
        batch_op.drop_index("idx_sd_station_name")
        batch_op.drop_index("idx_sd_station_callsign")

    op.drop_table("sd_stations")
    op.drop_table("sd_lineup_sync_status")
    with op.batch_alter_table("event_channel_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_channel_links_event_id"))
        batch_op.drop_index(batch_op.f("ix_event_channel_links_channel_id"))
        batch_op.drop_index("idx_event_channel_event")
        batch_op.drop_index("idx_event_channel_channel")

    op.drop_table("event_channel_links")
    with op.batch_alter_table("epg_programs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_epg_programs_title"))
        batch_op.drop_index(batch_op.f("ix_epg_programs_stop_time"))
        batch_op.drop_index(batch_op.f("ix_epg_programs_start_time"))
        batch_op.drop_index(batch_op.f("ix_epg_programs_epg_channel_id"))
        batch_op.drop_index("idx_epg_program_title")
        batch_op.drop_index("idx_epg_program_stop")
        batch_op.drop_index("idx_epg_program_start")
        batch_op.drop_index("idx_epg_program_channel_time")

    op.drop_table("epg_programs")
    with op.batch_alter_table("channel_links", schema=None) as batch_op:
        batch_op.drop_index("idx_channel_link_source")
        batch_op.drop_index("idx_channel_link_channel")

    op.drop_table("channel_links")
    with op.batch_alter_table("channel_health_status", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_health_status_status"))
        batch_op.drop_index("idx_health_status_status")

    op.drop_table("channel_health_status")
    with op.batch_alter_table("channel_health_checks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_health_checks_checked_at"))
        batch_op.drop_index(batch_op.f("ix_channel_health_checks_channel_id"))
        batch_op.drop_index("idx_health_check_result")
        batch_op.drop_index("idx_health_check_channel_time")

    op.drop_table("channel_health_checks")
    with op.batch_alter_table("channel_epg_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_epg_mappings_epg_channel_id"))
        batch_op.drop_index(batch_op.f("ix_channel_epg_mappings_channel_id"))
        batch_op.drop_index("idx_epg_channel_mapping")
        batch_op.drop_index("idx_channel_epg_channel")

    op.drop_table("channel_epg_mappings")
    with op.batch_alter_table("sd_lineups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sd_lineups_epg_source_id"))

    op.drop_table("sd_lineups")
    with op.batch_alter_table("epg_channels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_epg_channels_source_id"))
        batch_op.drop_index(batch_op.f("ix_epg_channels_channel_id"))
        batch_op.drop_index("idx_epg_channel_id")

    op.drop_table("epg_channels")
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channels_thesportsdb_id"))
        batch_op.drop_index(batch_op.f("ix_channels_ppv_enrichment_status"))
        batch_op.drop_index(batch_op.f("ix_channels_ppv_enrichment_queue_id"))
        batch_op.drop_index(batch_op.f("ix_channels_name"))
        batch_op.drop_index(batch_op.f("ix_channels_is_ppv"))
        batch_op.drop_index(batch_op.f("ix_channels_fcc_facility_id"))
        batch_op.drop_index(batch_op.f("ix_channels_category_id"))
        batch_op.drop_index(batch_op.f("ix_channels_account_id"))
        batch_op.drop_index("ix_channel_ppv_queue")
        batch_op.drop_index("idx_channel_name")
        batch_op.drop_index("idx_channel_category")
        batch_op.drop_index("idx_channel_account")

    op.drop_table("channels")
    with op.batch_alter_table("active_streams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_active_streams_credential_id"))

    op.drop_table("active_streams")
    with op.batch_alter_table("xtream_credentials", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_xtream_credentials_username"))
        batch_op.drop_index(batch_op.f("ix_xtream_credentials_playlist_config_id"))
        batch_op.drop_index(batch_op.f("ix_xtream_credentials_account_id"))

    op.drop_table("xtream_credentials")
    op.drop_table("tag_rules")
    op.drop_table("filters")
    with op.batch_alter_table("epg_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_epg_sources_account_id"))

    op.drop_table("epg_sources")
    op.drop_table("epg_match_rules")
    with op.batch_alter_table("credentials", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_credentials_account_id"))

    op.drop_table("credentials")
    with op.batch_alter_table("channel_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_tags_tag_id"))
        batch_op.drop_index(batch_op.f("ix_channel_tags_source"))
        batch_op.drop_index(batch_op.f("ix_channel_tags_account_id"))
        batch_op.drop_index("idx_channel_tags_account_tag")
        batch_op.drop_index("idx_channel_tags_account_stream")

    op.drop_table("channel_tags")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_is_ppv"))
        batch_op.drop_index(batch_op.f("ix_categories_account_id"))
        batch_op.drop_index("idx_category_ppv")
        batch_op.drop_index("idx_category_account")

    op.drop_table("categories")
    op.drop_table("account_rulesets")
    op.drop_table("account_epg_match_rulesets")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_name"))

    op.drop_table("tags")
    op.drop_table("sync_metadata")
    with op.batch_alter_table("sports_teams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sports_teams_sport"))
        batch_op.drop_index(batch_op.f("ix_sports_teams_name"))
        batch_op.drop_index(batch_op.f("ix_sports_teams_abbreviation"))
        batch_op.drop_index("idx_sports_team_sport")
        batch_op.drop_index("idx_sports_team_name")

    op.drop_table("sports_teams")
    op.drop_table("settings")
    op.drop_table("rulesets")
    op.drop_table("quality_tags")
    with op.batch_alter_table("provider_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_settings_provider_name"))

    op.drop_table("provider_settings")
    with op.batch_alter_table("playlist_configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_playlist_configs_slug"))

    op.drop_table("playlist_configs")
    op.drop_table("fcc_match_strategies")
    op.drop_table("fcc_match_networks")
    op.drop_table("fcc_match_location_patterns")
    op.drop_table("fcc_match_channel_patterns")
    with op.batch_alter_table("fcc_facilities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fcc_facilities_facility_id"))
        batch_op.drop_index(batch_op.f("ix_fcc_facilities_community_state"))
        batch_op.drop_index(batch_op.f("ix_fcc_facilities_community_city"))
        batch_op.drop_index(batch_op.f("ix_fcc_facilities_callsign"))
        batch_op.drop_index("idx_fcc_network")
        batch_op.drop_index("idx_fcc_dma")
        batch_op.drop_index("idx_fcc_city_state")
        batch_op.drop_index("idx_fcc_callsign_service")

    op.drop_table("fcc_facilities")
    with op.batch_alter_table("fcc_corrections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fcc_corrections_facility_id"))
        batch_op.drop_index(batch_op.f("ix_fcc_corrections_callsign"))

    op.drop_table("fcc_corrections")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_title"))
        batch_op.drop_index(batch_op.f("ix_events_status"))
        batch_op.drop_index(batch_op.f("ix_events_start_at"))
        batch_op.drop_index(batch_op.f("ix_events_sport"))
        batch_op.drop_index(batch_op.f("ix_events_scheduled_at"))
        batch_op.drop_index(batch_op.f("ix_events_league_name"))
        batch_op.drop_index(batch_op.f("ix_events_league_id"))
        batch_op.drop_index(batch_op.f("ix_events_is_ppv"))
        batch_op.drop_index(batch_op.f("ix_events_home_team_name"))
        batch_op.drop_index(batch_op.f("ix_events_home_team_id"))
        batch_op.drop_index(batch_op.f("ix_events_external_id"))
        batch_op.drop_index(batch_op.f("ix_events_away_team_name"))
        batch_op.drop_index(batch_op.f("ix_events_away_team_id"))
        batch_op.drop_index("idx_event_title")
        batch_op.drop_index("idx_event_teams")
        batch_op.drop_index("idx_event_scheduled")
        batch_op.drop_index("idx_event_league")

    op.drop_table("events")
    op.drop_table("epg_match_rulesets")
    op.drop_table("epg_exclusion_patterns")
    op.drop_table("epg_country_suffixes")
    op.drop_table("epg_channel_name_mappings")
    op.drop_table("country_tags")
    op.drop_table("channel_health_config")
    op.drop_table("callsign_suffixes")
    with op.batch_alter_table("cached_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cached_images_url_hash"))
        batch_op.drop_index("idx_cached_image_status")
        batch_op.drop_index("idx_cached_image_expires")

    op.drop_table("cached_images")
    op.drop_table("accounts")
    # ### end Alembic commands ###
