"""Persistent keys and default intervals for SyncScheduler jobs."""

DEFAULT_ACCOUNT_INTERVAL_HOURS = 6
DEFAULT_EPG_INTERVAL_HOURS = 12
DEFAULT_FCC_INTERVAL_HOURS = 168

SYNC_KEY_LAST_ACCOUNT_SYNC = "last_account_sync"
SYNC_KEY_LAST_FCC_SYNC = "last_fcc_sync"

SYNC_KEY_ACCOUNT_INTERVAL = "account_sync_interval_hours"
SYNC_KEY_EPG_INTERVAL = "epg_sync_interval_hours"
SYNC_KEY_FCC_INTERVAL = "fcc_sync_interval_hours"

SYNC_KEY_LAST_PPV_ENRICHMENT = "last_ppv_enrichment"
SYNC_KEY_LAST_PPV_PREFETCH = "last_ppv_prefetch"
DEFAULT_PPV_ENRICHMENT_INTERVAL_HOURS = 1
DEFAULT_PPV_PREFETCH_INTERVAL_HOURS = 6
SYNC_KEY_LAST_PPV_TIME_REFRESH = "last_ppv_time_refresh"
DEFAULT_PPV_TIME_REFRESH_INTERVAL_HOURS = 1

SYNC_KEY_LAST_SPORTSIPY_REFRESH = "last_sportsipy_refresh"
DEFAULT_SPORTSIPY_REFRESH_INTERVAL_HOURS = 168

SYNC_KEY_LAST_EPG_PROGRAM_CLEANUP = "last_epg_program_cleanup"
SYNC_KEY_LAST_HEALTH_CHECK_CLEANUP = "last_health_check_cleanup"
SYNC_KEY_LAST_EVENT_CLEANUP = "last_event_cleanup"
SYNC_KEY_LAST_IMAGE_CACHE_CLEANUP = "last_image_cache_cleanup"
DEFAULT_EPG_PROGRAM_CLEANUP_INTERVAL_HOURS = 24
DEFAULT_HEALTH_CHECK_CLEANUP_INTERVAL_HOURS = 168
DEFAULT_EVENT_CLEANUP_INTERVAL_HOURS = 168
DEFAULT_IMAGE_CACHE_CLEANUP_INTERVAL_HOURS = 24
DEFAULT_EPG_PROGRAM_RETENTION_DAYS = 7
DEFAULT_EVENT_RETENTION_DAYS = 90

SYNC_KEY_SCHEDULER_HEARTBEAT = "scheduler_heartbeat"
SCHEDULER_HEARTBEAT_TIMEOUT_SECONDS = 900

SYNC_FAILURE_AT_SUFFIX = "_failure_at"
SYNC_FAILURE_ERROR_SUFFIX = "_error"
MAX_SYNC_ERROR_LENGTH = 500
